/**
 * PHASE 3 CORRECTIVE §17 — THE PR #4 REVIEW INDEX CANNOT GO STALE UNNOTICED.
 *
 * `docs/PHASE_3_REVIEW_INDEX.md` is generated by `scripts/phase3-review-index.ts`
 * and is a review aid, not a source of truth. This suite makes its staleness a
 * failure: a row naming a path that no longer exists, a changed production
 * path with no row, and any row that differs from the generator's output.
 *
 * Where there is no git history (the release archive, a shallow checkout) the
 * check is tree-only and says so; the red proofs below that need history run
 * on synthetic rows, so every one of them runs everywhere.
 *
 * Regenerate with `npm run index:phase3:review` after committing.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  CHECK_COMMAND,
  INDEX_PATH,
  type Row,
  checkIndex,
  compareIndex,
  compareTreeOnly,
  groupOf,
  headerPurpose,
  namedSlice,
  parseRows,
  readTree,
  renderIndex,
  resolveSpecifier,
  securityOf,
  treeColumns,
} from '../../scripts/phase3-review-index';

const ROOT = join(__dirname, '../..');
const committed = (): string => readFileSync(join(ROOT, INDEX_PATH), 'utf8');

const row = (path: string, extra: Partial<Row> = {}): Row => ({
  path,
  group: groupOf(path),
  slice: 'P3-S4',
  purpose: `the purpose of ${path}`,
  checkpoint: '43b8370 (S4 freeze)',
  security: 'standard',
  tests: '1: integration/example',
  ...extra,
});

const SYNTHETIC: readonly Row[] = [
  row('apps/api/src/modules/purchasing/purchases.controller.ts'),
  row('infrastructure/database/migrations/0064_purchase_commands.sql', { security: 'high: migration, definer, grants' }),
  row('packages/inventory/src/landed-cost.ts'),
  row('tests/integration/purchase-s4-receipt.test.ts', { security: '', tests: '' }),
  row('docs/PHASE_3_S4_CONTRACT.md', { security: '', tests: '' }),
];
const everyPathExists = (): boolean => true;
const lineOf = (text: string, path: string): string => {
  const line = text.split('\n').find((l) => l.startsWith(`| \`${path}\` |`));
  if (line === undefined) throw new Error(`no row for ${path}`);
  return line;
};

describe('the committed review index', () => {
  it(`is current (${CHECK_COMMAND})`, () => {
    const result = checkIndex(ROOT);
    expect(result.problems).toEqual([]);
    if (result.mode === 'tree-only') expect(result.reason, 'a tree-only check states why it is not full').toMatch(/\S/);
    else expect(result.reason).toBeNull();
  });

  it('says at the top that it is a review aid, not a source of truth', () => {
    expect(committed().split('\n').slice(0, 4).join('\n')).toMatch(/A review aid, not a source of truth/);
  });

  it('has a row for every path the index names and no duplicate', () => {
    const paths = parseRows(committed()).map((r) => r.path);
    expect(paths.length).toBeGreaterThan(0);
    expect(new Set(paths).size).toBe(paths.length);
    expect(paths).not.toContain(INDEX_PATH);
  });
});

describe('red: the full comparison refuses a stale page', () => {
  const expected = renderIndex(SYNTHETIC);

  it('green twin: the generator output against itself', () => {
    expect(compareIndex(expected, expected, everyPathExists)).toEqual([]);
  });

  it('a planted row naming a path that no longer exists', () => {
    const planted = expected.replace(
      lineOf(expected, 'packages/inventory/src/landed-cost.ts'),
      `${lineOf(expected, 'packages/inventory/src/landed-cost.ts')}\n| \`packages/inventory/src/gone.ts\` | P3-S4 | removed | 43b8370 (S4 freeze) | standard | none found by reference |`,
    );
    const problems = compareIndex(planted, expected, (p) => p !== 'packages/inventory/src/gone.ts');
    expect(problems).toHaveLength(1);
    expect(problems[0]).toMatch(/^line \d+: names a path that no longer exists: packages\/inventory\/src\/gone\.ts$/);
  });

  it('a changed production path with no row', () => {
    const planted = expected.replace(`${lineOf(expected, 'apps/api/src/modules/purchasing/purchases.controller.ts')}\n`, '');
    expect(compareIndex(planted, expected, everyPathExists)).toEqual(['misses a changed path: apps/api/src/modules/purchasing/purchases.controller.ts']);
  });

  it('a row whose cells are stale (planted purpose, planted protected-by)', () => {
    const migration = lineOf(expected, 'infrastructure/database/migrations/0064_purchase_commands.sql');
    const planted = expected.replace(migration, migration.replace('1: integration/example', '0: nothing'));
    const problems = compareIndex(planted, expected, everyPathExists);
    expect(problems).toHaveLength(1);
    expect(problems[0]).toMatch(/^line \d+: stale row: infrastructure\/database\/migrations\/0064_purchase_commands\.sql$/);

    const controller = lineOf(expected, 'apps/api/src/modules/purchasing/purchases.controller.ts');
    const plantedPurpose = expected.replace(controller, controller.replace('the purpose of', 'an old purpose of'));
    expect(compareIndex(plantedPurpose, expected, everyPathExists)).toEqual([
      expect.stringMatching(/stale row: apps\/api\/src\/modules\/purchasing\/purchases\.controller\.ts$/),
    ]);
  });

  it('a row for an existing path Phase 3 did not change', () => {
    const planted = `${expected}| \`apps/api/src/main.ts\` | P3-S1 | x | 61b89d6 (S1 closure) | standard | none found by reference |\n`;
    expect(compareIndex(planted, expected, everyPathExists)).toEqual([expect.stringMatching(/names a path Phase 3 did not change: apps\/api\/src\/main\.ts$/)]);
  });

  it('stale text outside the rows', () => {
    const planted = expected.replace('## Summary', '## Summary (edited by hand)');
    expect(compareIndex(planted, expected, everyPathExists)).toEqual([expect.stringMatching(/^stale text at line \d+$/)]);
  });
});

describe('red: the checks on the real tree refuse a planted stale row', () => {
  it('the tree-only comparison: a vanished path and a stale protected-by cell on the committed page', () => {
    const page = committed();
    const tree = readTree(ROOT);
    const paths = parseRows(page).map((r) => r.path);
    const columns = treeColumns(tree, paths);
    const exists = (p: string): boolean => tree.files.has(p);
    expect(compareTreeOnly(page, columns, exists)).toEqual([]);

    const target = parseRows(page).find((r) => r.path === 'apps/api/src/modules/purchasing/purchases.controller.ts');
    expect(target).toBeDefined();
    const original = lineOf(page, 'apps/api/src/modules/purchasing/purchases.controller.ts');
    const staleCell = original.replace(/\| [^|]+ \|$/, '| 0: nothing |');
    const planted = page
      .replace(
        original,
        `${staleCell}\n| \`apps/api/src/modules/purchasing/purchase-gone.service.ts\` | P3-S4 | x | 43b8370 (S4 freeze) | standard | none found by reference |`,
      )
      .replace(/\n$/, '\n');
    const problems = compareTreeOnly(planted, columns, exists);
    expect(problems).toHaveLength(2);
    expect(problems.join('\n')).toMatch(/stale protected-by cell: apps\/api\/src\/modules\/purchasing\/purchases\.controller\.ts/);
    expect(problems.join('\n')).toMatch(/names a path that no longer exists: apps\/api\/src\/modules\/purchasing\/purchase-gone\.service\.ts/);
  });

  it('the full check of the repository: a planted row naming a vanished path fails it', () => {
    const page = committed();
    const anchor = lineOf(page, 'apps/api/src/modules/purchasing/purchases.controller.ts');
    const planted = page.replace(
      anchor,
      `${anchor}\n| \`apps/api/src/modules/purchasing/purchase-gone.service.ts\` | P3-S4 | x | 43b8370 (S4 freeze) | standard | none found by reference |`,
    );
    const result = checkIndex(ROOT, planted);
    expect(result.problems).toEqual(
      expect.arrayContaining([expect.stringMatching(/names a path that no longer exists: apps\/api\/src\/modules\/purchasing\/purchase-gone\.service\.ts$/)]),
    );
  });
});

describe('the derivation rules', () => {
  it.each([
    ['feat(p3-s4): suppliers', 'P3-S4'],
    ['test(s6): settlement', 'P3-S6'],
    ['test(p3-s3..s5): count jtis', 'P3-S3'],
    ['P3-S3: close the review findings', 'P3-S3'],
    ['feat(inventory): P3-S2 fixed-point valuation package', 'P3-S2'],
    ['docs(phase-3): P3-S0 architecture closure round 5', 'P3-S0'],
    ['fix(p3-corrective): TD-19 client IP', 'corrective'],
    ['feat(inventory): merchant-only invctl/1 minter', null],
    ['fix(release): gate:phase2:release protects the Phase 2 prefix', null],
  ])('namedSlice(%j) = %j', (subject, slice) => {
    expect(namedSlice(subject)).toBe(slice);
  });

  it.each([
    ['infrastructure/database/migrations/0069_inventory_reconciliation_read_and_account_domain.sql', 'db'],
    ['packages/inventory/src/valuation.ts', 'packages'],
    ['packages/inventory/test/valuation.test.ts', 'tests'],
    ['packages/inventory/vectors/invpl-vectors.json', 'tests'],
    ['apps/api/src/config.ts', 'api'],
    ['apps/web/src/lib/csp.ts', 'web'],
    ['apps/web/test/csp.test.ts', 'tests'],
    ['scripts/guards/posting-surface.ts', 'security'],
    ['scripts/phase3-s8-gate.ts', 'security'],
    ['scripts/phase3-release-gate.ts', 'ci'],
    ['scripts/export-release.ts', 'ci'],
    ['.github/workflows/ci.yml', 'ci'],
    ['package.json', 'ci'],
    ['tests/helpers/scratch-db.ts', 'tests'],
    ['docs/PHASE_3_S9_RELEASE.md', 'docs'],
    ['PROJECT_STATUS.md', 'docs'],
  ])('groupOf(%j) = %j', (path, group) => {
    expect(groupOf(path)).toBe(group);
  });

  it('security relevance names each matching rule', () => {
    expect(securityOf('infrastructure/database/migrations/0070_x.sql', 'CREATE FUNCTION f() SECURITY DEFINER; GRANT EXECUTE ON FUNCTION f() TO a;')).toBe(
      'high: migration, definer, grants',
    );
    expect(securityOf('.github/workflows/ci.yml', 'on: push')).toBe('high: workflow');
    expect(securityOf('apps/web/src/app/api/proxy/[...path]/route.ts', '')).toBe('high: auth');
    expect(securityOf('apps/api/src/modules/inventory/inventory-assertion.minter.ts', '')).toBe('high: assertion');
    expect(securityOf('apps/web/src/views/stock/parts.tsx', 'export const x = 1;')).toBe('standard');
  });

  it('a purpose is the first paragraph of the leading comment, without the file name a migration opens with', () => {
    expect(
      headerPurpose('infrastructure/database/migrations/0099_x.sql', '-- 0099_x.sql\n-- Phase 3 corrective — the thing it does.\n-- More.\n\nSELECT 1;\n'),
    ).toBe('Phase 3 corrective — the thing it does.');
    expect(headerPurpose('scripts/x.ts', '#!/usr/bin/env tsx\n/**\n * ────\n * THE GATE — what it is\n * ────\n *\n * Body.\n */\n')).toBe(
      'THE GATE — what it is',
    );
    expect(headerPurpose('apps/api/src/x.service.ts', "import { A } from 'a';\n\n/** The service. More words. */\n@Injectable()\nexport class X {}\n")).toBe(
      'The service.',
    );
    expect(headerPurpose('docs/X.md', '# Title / عنوان\n\ntext')).toBe('Title / عنوان');
    expect(headerPurpose('apps/web/src/messages/en.json', '{}')).toBeNull();
  });

  it('imports resolve to repository files, including the web alias and the workspace packages', () => {
    const files = new Set(['apps/web/src/lib/csp.ts', 'packages/inventory/src/index.ts', 'apps/api/src/config.ts', 'apps/web/src/messages/en.json']);
    expect(resolveSpecifier(files, 'apps/web/test/csp.test.ts', '@/lib/csp')).toBe('apps/web/src/lib/csp.ts');
    expect(resolveSpecifier(files, 'apps/web/test/jargon.test.ts', '@/messages/en.json')).toBe('apps/web/src/messages/en.json');
    expect(resolveSpecifier(files, 'tests/integration/x.test.ts', '@daftar/inventory')).toBe('packages/inventory/src/index.ts');
    expect(resolveSpecifier(files, 'tests/integration/x.test.ts', '../../apps/api/src/config')).toBe('apps/api/src/config.ts');
    expect(resolveSpecifier(files, 'tests/integration/x.test.ts', 'vitest')).toBeNull();
  });
});
