/**
 * `invpl/1` — the canonical inventory command payload (P3-AL-55 §F).
 *
 * An `invctl/1` assertion authorizes THE PAYLOAD THE ROUTINE ACTUALLY
 * RECEIVES. Component 7 of the assertion is the SHA-256 of the stream built
 * here; the database routine rebuilds the same stream from its OWN arguments
 * and refuses a mismatch (`inventory.assertion_payload_mismatch`) before any
 * decision-relevant read or write. A caller-supplied digest is never trusted
 * by itself — the principle of `acctfp/1` (`packages/accounting/src/fingerprint.ts`).
 *
 * The stream, every line terminated by the single byte 0x0A (LF), the last
 * one included:
 *
 *   'invpl/1' LF  op_code LF  tenant LF  business LF  field_1 LF … field_n LF
 *
 * Field encoding — no implementer choice:
 *
 *   UUID      36 bytes, lowercase hex, hyphenated 8-4-4-4-12
 *   boolean   ASCII `true` / `false`
 *   integer   base-10 ASCII; `-` only for a negative value; no `+`, no leading
 *             zero; zero is `0`
 *   code      its bytes exactly; must already match ^[a-z][a-z0-9_]{0,31}$
 *   NULL      the single byte 0x00 and nothing else on that line
 *
 * Non-canonical input is REFUSED, never normalized: an uppercase UUID, a code
 * with a capital letter or a trailing space, a fractional or unsafe integer.
 * Normalizing here would let the application sign bytes the database would
 * never produce from the same arguments, and the two implementations would
 * agree with themselves while disagreeing with each other.
 *
 * The same specification is implemented in SQL; both are tested against
 * `vectors/invpl-vectors.json`, generated by `scripts/generate-vectors.ts`.
 */
import { createHash } from 'node:crypto';
import { InventoryError } from './errors';

/**
 * The operation kinds P3-S1 registers (P3-AL-55 §E). Later slices register
 * their own kinds together with the routine that consumes them; a kind listed
 * here without a routine would be an authority nothing refuses.
 */
export type InventoryS1OperationCode = 'inventory.configure_product' | 'structure.associate_warehouse_branch' | 'structure.dissociate_warehouse_branch';

/**
 * The seven operation kinds P3-S3 registers (L:1912-1922; PHASE_3_S3_CONTRACT
 * A-01, §2.5), one per entry routine of `0062`. Stocktake cancel is the
 * `cancelled` outcome of `inventory.stocktake_finalize`, never an eighth kind
 * (A-11, TL-3).
 */
export type InventoryS3OperationCode =
  | 'inventory.transfer'
  | 'inventory.adjust'
  | 'inventory.damage'
  | 'inventory.stocktake_open'
  | 'inventory.stocktake_count'
  | 'inventory.stocktake_finalize'
  | 'inventory.opening';

/**
 * The seven operation kinds P3-S4 registers (PHASE_3_S4_CONTRACT A-03, §2.5),
 * one per entry routine of `0064`, named for the command (L:1926). Supplier
 * reactivation is its own kind rather than a direction flag (TL-3).
 */
export type InventoryS4OperationCode =
  | 'supplier.create'
  | 'supplier.update'
  | 'supplier.archive'
  | 'supplier.reactivate'
  | 'purchase.draft'
  | 'purchase.cancel'
  | 'purchase.receive';

/**
 * The two operation kinds P3-S5 registers (PHASE_3_S5_CONTRACT A-03, §2.6),
 * one per entry routine of `0066`, named for the command (L:1926).
 */
export type InventoryS5OperationCode = 'purchase.return' | 'purchase.reverse';

/**
 * The seven operation kinds P3-S6 registers (PHASE_3_S6_CONTRACT A-03, §2.6),
 * one per entry routine of `0068`. The payment-method kinds are
 * `payment.<verb>_method`: the registry grammar admits no underscore in the
 * first segment, so `payment_method.create` could not be registered.
 */
export type InventoryS6OperationCode =
  | 'payment.create_method'
  | 'payment.update_method'
  | 'payment.deactivate_method'
  | 'payment.activate_method'
  | 'supplier.pay'
  | 'supplier.allocate_credit'
  | 'supplier.receive_refund';

/**
 * The one operation kind the Phase 3 corrective pass registers (0072, TD-16:
 * `registered_by = 'P3-C'`): the write-off of a purchase's sub-unit AP
 * residue, routine `purchase_write_off_residue`.
 */
export type InventoryCorrectiveOperationCode = 'purchase.write_off_residue';

/**
 * The four operation kinds P4-S1 registers (lock P4-AL-39, gap G-5).
 *
 * A customer write needs a signed server decision like every other Phase 4
 * write: `P4-AL-38` gives `daftar_app` no DML on any Phase 4 table, and
 * `P4-AL-39` requires every Phase 4 definer routine to verify one. A customer
 * posts nothing to the ledger, so the assertion it verifies is the `invctl/1`
 * inventory assertion rather than the accounting one — by elimination, and
 * following the P3-S4 SUPPLIER precedent exactly: a customer is the mirror of a
 * supplier, business-wide master data shared by every branch.
 *
 * `customer.<verb>`, singular first segment, because the registry grammar
 * `^[a-z]+(\.[a-z_]+)+$` (`0054:53`, duplicated at `0054:229`) admits no
 * underscore in the first segment — the same constraint that made P3-S6 write
 * `payment.<verb>_method`. The PERMISSION keys are plural (`customers.manage`,
 * P4-AL-36); an operation code and a permission key are different namespaces
 * with different grammars, and P3-S4 already pairs `supplier.create` with
 * `suppliers.manage`.
 *
 * Reactivation is its own kind rather than a direction flag, as P3-S4 ruled for
 * the supplier (TL-3).
 */
export type InventoryP4S1OperationCode = 'customer.create' | 'customer.update' | 'customer.archive' | 'customer.reactivate';

/**
 * The ONE operation kind P4-S2 registers (lock P4-AL-28, P4-AL-29; plan §6
 * S2 row).
 *
 * `sale.*` and `customer.*` are the Phase 4 namespaces, and the first segment
 * may hold no underscore: `op_code TEXT PRIMARY KEY CHECK (op_code ~
 * '^[a-z]+(\.[a-z_]+)+$')` (`0054:53`), with the SAME regex inside the frozen
 * body of `inventory_payload_digest` (`0054:229`). Widening either is
 * forbidden by P4-AL-27 and P4-AL-29, so the namespace is what changes.
 *
 * `sale.void` and `sale.return` are deliberately ABSENT. They belong to P4-S6
 * and P4-S5, and this file's own rule says why: "a kind listed here without a
 * routine would be an authority nothing refuses". `TL-P4-S1-R1` has just ruled
 * on the same mistake one layer up, for an accounting source type.
 */
export type InventoryP4S2OperationCode = 'sale.commit';

/**
 * The four operation kinds P4-S3 registers: the till session's two ends, and
 * the two writes a client may make to the server-side basket (lock P4-AL-18,
 * `OD-P4-02`, `OD-P4-09`).
 *
 * `pos.*` is the namespace, which is what the frozen `op_code` regex permits
 * to change (`^[a-z]+(\.[a-z_]+)+$`, `0054:53` and the identical copy inside
 * the frozen body of `inventory_payload_digest` at `0054:229`); widening
 * either is forbidden by P4-AL-27 and P4-AL-29.
 *
 * There are exactly four because `0079` creates exactly four routines that
 * consume an `invctl/1` assertion, and this file's standing rule is that "a
 * kind listed here without a routine would be an authority nothing refuses".
 * `pos.sale_commit` is deliberately ABSENT: a sale rung up on a till commits
 * through the accepted `sale.commit` of P4-S2, which is the whole reason the
 * basket is a separate relation from the sale.
 */
export type InventoryP4S3OperationCode = 'pos.session_open' | 'pos.session_close' | 'pos.cart_set_line' | 'pos.cart_remove_line';

export type InventoryOperationCode =
  | InventoryS1OperationCode
  | InventoryS3OperationCode
  | InventoryS4OperationCode
  | InventoryS5OperationCode
  | InventoryS6OperationCode
  | InventoryCorrectiveOperationCode
  | InventoryP4S1OperationCode
  | InventoryP4S2OperationCode
  | InventoryP4S3OperationCode;

export const INVENTORY_S1_OPERATION_CODES: readonly InventoryS1OperationCode[] = [
  'inventory.configure_product',
  'structure.associate_warehouse_branch',
  'structure.dissociate_warehouse_branch',
];

export const INVENTORY_S3_OPERATION_CODES: readonly InventoryS3OperationCode[] = [
  'inventory.transfer',
  'inventory.adjust',
  'inventory.damage',
  'inventory.stocktake_open',
  'inventory.stocktake_count',
  'inventory.stocktake_finalize',
  'inventory.opening',
];

export const INVENTORY_S4_OPERATION_CODES: readonly InventoryS4OperationCode[] = [
  'supplier.create',
  'supplier.update',
  'supplier.archive',
  'supplier.reactivate',
  'purchase.draft',
  'purchase.cancel',
  'purchase.receive',
];

export const INVENTORY_S5_OPERATION_CODES: readonly InventoryS5OperationCode[] = ['purchase.return', 'purchase.reverse'];

export const INVENTORY_S6_OPERATION_CODES: readonly InventoryS6OperationCode[] = [
  'payment.create_method',
  'payment.update_method',
  'payment.deactivate_method',
  'payment.activate_method',
  'supplier.pay',
  'supplier.allocate_credit',
  'supplier.receive_refund',
];

export const INVENTORY_CORRECTIVE_OPERATION_CODES: readonly InventoryCorrectiveOperationCode[] = ['purchase.write_off_residue'];

export const INVENTORY_P4_S1_OPERATION_CODES: readonly InventoryP4S1OperationCode[] = [
  'customer.create',
  'customer.update',
  'customer.archive',
  'customer.reactivate',
];

export const INVENTORY_P4_S2_OPERATION_CODES: readonly InventoryP4S2OperationCode[] = ['sale.commit'];

export const INVENTORY_P4_S3_OPERATION_CODES: readonly InventoryP4S3OperationCode[] = [
  'pos.session_open',
  'pos.session_close',
  'pos.cart_set_line',
  'pos.cart_remove_line',
];

export const INVENTORY_OPERATION_CODES: readonly InventoryOperationCode[] = [
  ...INVENTORY_S1_OPERATION_CODES,
  ...INVENTORY_S3_OPERATION_CODES,
  ...INVENTORY_S4_OPERATION_CODES,
  ...INVENTORY_S5_OPERATION_CODES,
  ...INVENTORY_S6_OPERATION_CODES,
  ...INVENTORY_CORRECTIVE_OPERATION_CODES,
  ...INVENTORY_P4_S1_OPERATION_CODES,
  ...INVENTORY_P4_S2_OPERATION_CODES,
  ...INVENTORY_P4_S3_OPERATION_CODES,
];

/** The literal first line of every stream. */
export const INVPL_DOMAIN = 'invpl/1';

/** The registry's own CHECK on `inventory_operation_kinds.op_code`. */
export const OPERATION_CODE_RE = /^[a-z]+(\.[a-z_]+)+$/;
/** Canonical UUID: lowercase only. The pattern the database enforces. */
export const CANONICAL_UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
/** The `units.unit_code` registry pattern (P3-AL-05). */
export const REGISTRY_CODE_RE = /^[a-z][a-z0-9_]{0,31}$/;

/** The range of PostgreSQL `bigint`, the widest integer a routine argument can be. */
const INT8_MIN = -(2n ** 63n);
const INT8_MAX = 2n ** 63n - 1n;

const LF = 0x0a;
const NUL = 0x00;

/** One typed field of the stream. The type decides the encoding, never the value. */
export type InventoryPayloadField =
  | { readonly kind: 'uuid'; readonly value: string }
  | { readonly kind: 'boolean'; readonly value: boolean }
  | { readonly kind: 'integer'; readonly value: number | bigint }
  | { readonly kind: 'code'; readonly value: string }
  | { readonly kind: 'null' };

export type InventoryPayloadFieldType = Exclude<InventoryPayloadField['kind'], 'null'>;

export interface InventoryPayloadFieldSpec {
  readonly name: string;
  readonly type: InventoryPayloadFieldType;
  readonly nullable: boolean;
}

/**
 * A variable number of lines (PHASE_3_S3_CONTRACT A-09): the group of
 * `fields` repeats once per line, AFTER the whole header, as many times as
 * the header field `countField` says. Every group has a fixed width, so the
 * stream stays unambiguous under the locked four-type grammar.
 */
export interface InventoryPayloadRepeat {
  readonly countField: string;
  readonly fields: readonly InventoryPayloadFieldSpec[];
}

/**
 * A second variable group after the lines (PHASE_3_S4_CONTRACT A-09, the
 * landed costs of `purchase.draft`): the count field `countField` follows the
 * last line, then the group `fields` repeats that many times. When `perLine`
 * is set, each group ends with that field once per line of the first group —
 * one row of a `count × line_count` matrix, in line order. Every width is
 * fixed by counts already read, so the stream stays unambiguous.
 */
export interface InventoryPayloadTrailer {
  readonly countField: InventoryPayloadFieldSpec;
  readonly fields: readonly InventoryPayloadFieldSpec[];
  readonly perLine?: InventoryPayloadFieldSpec;
}

/**
 * The schema of one operation kind: the fixed header field list, in stream
 * order, plus — for a P3-S3 kind that carries lines — the repeating group
 * that follows it, and — for `purchase.draft` only — the trailer group after
 * the lines. A P3-S1 schema is a header and nothing else, exactly as it was
 * accepted.
 */
export type InventoryPayloadSchema = readonly InventoryPayloadFieldSpec[] & {
  readonly repeat?: InventoryPayloadRepeat;
  readonly trailer?: InventoryPayloadTrailer;
};

const spec = (name: string, type: InventoryPayloadFieldType, nullable = false): InventoryPayloadFieldSpec => Object.freeze({ name, type, nullable });

/** Eight unsigned 32-bit words of the reason's SHA-256 (A-09, TL-4). */
const REASON_WORDS: readonly InventoryPayloadFieldSpec[] = Array.from({ length: 8 }, (_, i) => spec(`reason_w${i + 1}`, 'integer'));

function withLines(header: readonly InventoryPayloadFieldSpec[], lineFields: readonly InventoryPayloadFieldSpec[]): InventoryPayloadSchema {
  return withGroup(header, 'line_count', lineFields);
}

/**
 * A header and one repeating group counted by `countField` (P3-S6: the
 * allocations of `supplier.pay`, counted by `allocation_count`). `withLines`
 * is this group under the S3 name `line_count`.
 */
function withGroup(
  header: readonly InventoryPayloadFieldSpec[],
  countField: string,
  groupFields: readonly InventoryPayloadFieldSpec[],
): InventoryPayloadSchema {
  const repeat: InventoryPayloadRepeat = Object.freeze({ countField, fields: Object.freeze([...groupFields]) });
  return Object.freeze(Object.assign([...header], { repeat }));
}

function withLinesAndTrailer(
  header: readonly InventoryPayloadFieldSpec[],
  lineFields: readonly InventoryPayloadFieldSpec[],
  trailer: InventoryPayloadTrailer,
): InventoryPayloadSchema {
  const repeat: InventoryPayloadRepeat = Object.freeze({ countField: 'line_count', fields: Object.freeze([...lineFields]) });
  return Object.freeze(Object.assign([...header], { repeat, trailer: Object.freeze({ ...trailer, fields: Object.freeze([...trailer.fields]) }) }));
}

/** Eight unsigned 32-bit words of a free text's SHA-256, `<prefix>_w1..w8`; eight NULLs for NULL text (PHASE_3_S4_CONTRACT A-09). */
const textWordSpecs = (prefix: string, nullable: boolean): readonly InventoryPayloadFieldSpec[] =>
  Array.from({ length: 8 }, (_, i) => spec(`${prefix}_w${i + 1}`, 'integer', nullable));

/** The five supplier word groups (A-09): the name is required, the rest may be NULL. */
const SUPPLIER_TEXT: readonly InventoryPayloadFieldSpec[] = [
  ...textWordSpecs('name', false),
  ...textWordSpecs('phone', true),
  ...textWordSpecs('email', true),
  ...textWordSpecs('tax_identifier', true),
  ...textWordSpecs('notes', true),
];

/**
 * The customer word groups (P4-S1, gap G-5): the SUPPLIER group of
 * `PHASE_3_S4_CONTRACT` A-09, built from the same `textWordSpecs` binding with
 * the same required-name / nullable-rest shape, because a customer is the
 * mirror of a supplier. The name is required; the rest may be NULL.
 *
 * It mirrors FOUR of the supplier's five groups and not the fifth. The
 * supplier's `tax_identifier` is deliberately absent, and its absence is a
 * ruling rather than an omission: P4-AL-44 records that the registered /
 * unregistered / exempt distinction "has no representation in the data model
 * yet", P4-AL-45 forbids inventing one while OD-03 is open, and the accepted
 * P4-S1 read contract states it outright — "no tax identifier and no
 * registration flag" (`packages/shared-contracts/src/customers.ts:25-28`), so
 * `CustomerFieldsDto` carries `name`, `phone`, `email` and `notes` and nothing
 * else. A signed field the routine has no argument for could never be rebuilt
 * in SQL anyway, so mirroring the fifth group would have been a stream the
 * database cannot reproduce as well as a legal policy this slice may not
 * invent.
 *
 * Also deliberately NOT here, each for the same kind of reason:
 *   - no credit limit — `OD-P4-03` is RULED OPTION A, no limit in Phase 4;
 *   - no balance, paid total, outstanding total or aging field — `P4-AL-06`
 *     forbids any stored authoritative one on any Phase 4 relation, and a
 *     signed payload field is the strongest possible form of storing one.
 */
const CUSTOMER_TEXT: readonly InventoryPayloadFieldSpec[] = [
  ...textWordSpecs('name', false),
  ...textWordSpecs('phone', true),
  ...textWordSpecs('email', true),
  ...textWordSpecs('notes', true),
];

/** The three optional payment-method name word groups (PHASE_3_S6_CONTRACT A-16): each NULL when that locale has no name. */
const PAYMENT_METHOD_NAMES: readonly InventoryPayloadFieldSpec[] = [
  ...textWordSpecs('name_ar', true),
  ...textWordSpecs('name_en', true),
  ...textWordSpecs('name_tr', true),
];

/**
 * Field order per operation kind (P3-AL-55 §F, P3-S1 table; PHASE_3_S3_CONTRACT
 * A-09 for the seven P3-S3 kinds). The SQL canonicalizer takes the routine's
 * arguments in exactly this order.
 *
 * A P3-S3 quantity or cost travels as its exact fixed-point integer — `_q4`
 * is a quantity × 10^4, `_c10` a unit cost × 10^10 — a value as signed minor
 * units, a date as the integer `YYYYMMDD` and a reason as the eight words of
 * its SHA-256. The grammar keeps its four types; no new type exists.
 */
export const INVENTORY_PAYLOAD_SCHEMAS: Readonly<Record<InventoryOperationCode, InventoryPayloadSchema>> = {
  'inventory.configure_product': [
    { name: 'product_id', type: 'uuid', nullable: false },
    { name: 'track_inventory', type: 'boolean', nullable: false },
    { name: 'unit_code', type: 'code', nullable: true },
    { name: 'unit_decimals', type: 'integer', nullable: true },
  ],
  'structure.associate_warehouse_branch': [
    { name: 'warehouse_id', type: 'uuid', nullable: false },
    { name: 'branch_id', type: 'uuid', nullable: false },
  ],
  'structure.dissociate_warehouse_branch': [
    { name: 'warehouse_id', type: 'uuid', nullable: false },
    { name: 'branch_id', type: 'uuid', nullable: false },
  ],
  'inventory.transfer': withLines(
    [spec('transfer_id', 'uuid'), spec('source_warehouse_id', 'uuid'), spec('destination_warehouse_id', 'uuid'), spec('line_count', 'integer')],
    [spec('variant_id', 'uuid'), spec('qty_q4', 'integer')],
  ),
  'inventory.adjust': withLines(
    [spec('adjustment_id', 'uuid'), spec('warehouse_id', 'uuid'), spec('occurred_on', 'integer'), ...REASON_WORDS, spec('line_count', 'integer')],
    [spec('variant_id', 'uuid'), spec('qty_delta_q4', 'integer'), spec('unit_cost_c10', 'integer', true), spec('expected_value', 'integer')],
  ),
  'inventory.damage': withLines(
    [spec('adjustment_id', 'uuid'), spec('warehouse_id', 'uuid'), spec('occurred_on', 'integer'), ...REASON_WORDS, spec('line_count', 'integer')],
    [spec('variant_id', 'uuid'), spec('qty_q4', 'integer'), spec('expected_value', 'integer')],
  ),
  'inventory.stocktake_open': Object.freeze([spec('stocktake_id', 'uuid'), spec('warehouse_id', 'uuid')]),
  'inventory.stocktake_count': withLines(
    [spec('stocktake_id', 'uuid'), spec('warehouse_id', 'uuid'), spec('line_count', 'integer')],
    [spec('variant_id', 'uuid'), spec('counted_q4', 'integer')],
  ),
  'inventory.stocktake_finalize': withLines(
    [spec('stocktake_id', 'uuid'), spec('warehouse_id', 'uuid'), spec('outcome', 'code'), spec('occurred_on', 'integer', true), spec('line_count', 'integer')],
    [spec('variant_id', 'uuid'), spec('variance_q4', 'integer'), spec('unit_cost_c10', 'integer', true), spec('expected_value', 'integer')],
  ),
  'inventory.opening': withLines(
    [
      spec('opening_id', 'uuid'),
      spec('occurred_on', 'integer'),
      spec('opening_balance_id', 'uuid', true),
      spec('position_minor', 'integer', true),
      spec('line_count', 'integer'),
    ],
    [spec('warehouse_id', 'uuid'), spec('variant_id', 'uuid'), spec('qty_q4', 'integer'), spec('unit_cost_c10', 'integer')],
  ),
  // P3-S4 (PHASE_3_S4_CONTRACT A-09). Money is integer txn minor units, a
  // unit price the C10 of a txn minor unit, a currency its lowercase ISO
  // code, a rate its R10 (rate x 10^10) and a rate instant epoch seconds.
  'supplier.create': Object.freeze([spec('supplier_id', 'uuid'), ...SUPPLIER_TEXT]),
  'supplier.update': Object.freeze([spec('supplier_id', 'uuid'), spec('expected_revision', 'integer'), ...SUPPLIER_TEXT]),
  'supplier.archive': Object.freeze([spec('supplier_id', 'uuid'), spec('expected_revision', 'integer')]),
  'supplier.reactivate': Object.freeze([spec('supplier_id', 'uuid'), spec('expected_revision', 'integer')]),
  'purchase.draft': withLinesAndTrailer(
    [
      spec('purchase_id', 'uuid'),
      spec('expected_revision', 'integer'),
      spec('supplier_id', 'uuid'),
      spec('warehouse_id', 'uuid'),
      spec('previous_warehouse_id', 'uuid', true),
      spec('currency', 'code'),
      spec('document_date', 'integer'),
      ...textWordSpecs('supplier_reference', true),
      ...textWordSpecs('notes', true),
      spec('tax_minor', 'integer'),
      spec('line_count', 'integer'),
    ],
    [spec('line_id', 'uuid'), spec('variant_id', 'uuid'), spec('qty_q4', 'integer'), spec('unit_price_c10', 'integer'), spec('discount_minor', 'integer')],
    {
      countField: spec('landed_count', 'integer'),
      fields: [spec('landed_cost_id', 'uuid'), spec('mode', 'code'), spec('amount_minor', 'integer'), ...textWordSpecs('description', true)],
      perLine: spec('allocation_minor', 'integer', true),
    },
  ),
  'purchase.cancel': Object.freeze([spec('purchase_id', 'uuid'), spec('warehouse_id', 'uuid'), spec('draft_revision', 'integer')]),
  'purchase.receive': withLines(
    [
      spec('purchase_id', 'uuid'),
      spec('warehouse_id', 'uuid'),
      spec('draft_revision', 'integer'),
      spec('supplier_id', 'uuid'),
      spec('supplier_revision', 'integer'),
      spec('document_date', 'integer'),
      spec('currency', 'code'),
      spec('rate_id', 'uuid', true),
      spec('rate_r10', 'integer'),
      spec('rate_source', 'code'),
      spec('rate_at', 'integer'),
      spec('total_txn_minor', 'integer'),
      spec('total_base_minor', 'integer'),
      spec('coverage_adjustment_id', 'uuid', true),
      spec('line_count', 'integer'),
    ],
    [
      spec('line_id', 'uuid'),
      spec('variant_id', 'uuid'),
      spec('qty_q4', 'integer'),
      spec('base_share_minor', 'integer'),
      spec('covered_q4', 'integer'),
      spec('catch_up_minor', 'integer'),
    ],
  ),
  // P3-S5 (PHASE_3_S5_CONTRACT A-17). Every amount is an integer minor unit:
  // `*_txn` in the purchase currency, the rest in base; `ppv` is signed. The
  // return's reason is optional (eight NULL words), the reversal's required.
  'purchase.return': withLines(
    [
      spec('return_id', 'uuid'),
      spec('purchase_id', 'uuid'),
      spec('warehouse_id', 'uuid'),
      spec('document_date', 'integer'),
      ...textWordSpecs('reason', true),
      spec('credit_note_id', 'uuid', true),
      spec('carrying_txn', 'integer'),
      spec('ap_txn', 'integer'),
      spec('ap_base', 'integer'),
      spec('credit_txn', 'integer'),
      spec('credit_base', 'integer'),
      spec('inventory_value', 'integer'),
      spec('ppv', 'integer'),
      spec('line_count', 'integer'),
    ],
    [
      spec('return_line_id', 'uuid'),
      spec('purchase_line_id', 'uuid'),
      spec('variant_id', 'uuid'),
      spec('qty_q4', 'integer'),
      spec('carrying_txn', 'integer'),
      spec('value_out', 'integer'),
    ],
  ),
  'purchase.reverse': withLines(
    [
      spec('purchase_id', 'uuid'),
      spec('warehouse_id', 'uuid'),
      spec('reversal_date', 'integer'),
      ...textWordSpecs('reason', false),
      spec('original_entry_id', 'uuid'),
      spec('total_value', 'integer'),
      spec('line_count', 'integer'),
    ],
    [spec('line_id', 'uuid'), spec('variant_id', 'uuid'), spec('qty_q4', 'integer'), spec('value', 'integer')],
  ),
  // P3-S6 (PHASE_3_S6_CONTRACT A-16). Every amount is an integer minor unit
  // of the currency its row names (`*_dust` and `realized` in base, signed);
  // a currency is its lowercase ISO code, a rate its R10, a rate instant epoch
  // seconds, a date `YYYYMMDD`, a text the eight words of its SHA-256 (eight
  // NULLs for NULL).
  'payment.create_method': Object.freeze([
    spec('payment_method_id', 'uuid'),
    spec('system_type', 'code'),
    spec('posting_account_id', 'uuid'),
    spec('requires_reference', 'boolean'),
    spec('sort_order', 'integer'),
    ...PAYMENT_METHOD_NAMES,
  ]),
  'payment.update_method': Object.freeze([
    spec('payment_method_id', 'uuid'),
    spec('expected_revision', 'integer'),
    spec('posting_account_id', 'uuid'),
    spec('requires_reference', 'boolean'),
    spec('sort_order', 'integer'),
    ...PAYMENT_METHOD_NAMES,
  ]),
  'payment.deactivate_method': Object.freeze([spec('payment_method_id', 'uuid'), spec('expected_revision', 'integer')]),
  'payment.activate_method': Object.freeze([spec('payment_method_id', 'uuid'), spec('expected_revision', 'integer')]),
  'supplier.pay': withGroup(
    [
      spec('payment_id', 'uuid'),
      spec('supplier_id', 'uuid'),
      spec('payment_method_id', 'uuid'),
      spec('posting_account_id', 'uuid'),
      spec('payment_date', 'integer'),
      spec('currency', 'code'),
      spec('amount', 'integer'),
      spec('rate_id', 'uuid', true),
      spec('rate', 'integer'),
      spec('rate_source', 'code'),
      spec('rate_at', 'integer'),
      spec('base_amount', 'integer'),
      ...textWordSpecs('reference', true),
      spec('allocation_count', 'integer'),
    ],
    'allocation_count',
    [
      spec('allocation_id', 'uuid'),
      spec('purchase_id', 'uuid'),
      spec('warehouse_id', 'uuid'),
      spec('purchase_currency', 'code'),
      spec('payment_amount', 'integer'),
      spec('payment_base', 'integer'),
      spec('applied', 'integer'),
      spec('released_before', 'integer'),
      spec('carrying_released', 'integer'),
      spec('ap_dust', 'integer'),
      spec('realized', 'integer'),
    ],
  ),
  'supplier.allocate_credit': Object.freeze([
    spec('allocation_id', 'uuid'),
    spec('credit_note_id', 'uuid'),
    spec('purchase_id', 'uuid'),
    spec('warehouse_id', 'uuid'),
    spec('allocation_date', 'integer'),
    spec('credit_currency', 'code'),
    spec('consumed', 'integer'),
    spec('remaining_before', 'integer'),
    spec('credit_released', 'integer'),
    spec('credit_dust', 'integer'),
    spec('purchase_currency', 'code'),
    spec('applied', 'integer'),
    spec('ap_released_before', 'integer'),
    spec('ap_released', 'integer'),
    spec('ap_dust', 'integer'),
    spec('realized', 'integer'),
  ]),
  'supplier.receive_refund': Object.freeze([
    spec('refund_id', 'uuid'),
    spec('credit_note_id', 'uuid'),
    spec('payment_method_id', 'uuid'),
    spec('posting_account_id', 'uuid'),
    spec('refund_date', 'integer'),
    spec('source_currency', 'code'),
    spec('consumed', 'integer'),
    spec('remaining_before', 'integer'),
    spec('source_released', 'integer'),
    spec('source_dust', 'integer'),
    spec('receipt_currency', 'code'),
    spec('receipt_amount', 'integer'),
    spec('rate_id', 'uuid', true),
    spec('rate', 'integer'),
    spec('rate_source', 'code'),
    spec('rate_at', 'integer'),
    spec('receipt_base', 'integer'),
    spec('realized', 'integer'),
    ...textWordSpecs('reference', true),
  ]),
  // Phase 3 corrective (0072, TD-16): the write-off's own arguments. The
  // residue is the client's statement of O; the chain point and the base it
  // releases are derived.
  'purchase.write_off_residue': Object.freeze([
    spec('purchase_id', 'uuid'),
    spec('write_off_date', 'integer'),
    ...textWordSpecs('reason', false),
    spec('residue', 'integer'),
    spec('released_before', 'integer'),
    spec('residue_base', 'integer'),
  ]),
  // P4-S1 (lock P4-AL-39, gap G-5). A customer is business-wide master data and
  // follows the P3-S4 supplier payload: the id, the optimistic revision on
  // every edit, then the free-text word groups (`CUSTOMER_TEXT` — the supplier
  // groups less the tax identifier P4-AL-44/45 forbid). Every field is client
  // intent, so these kinds get NO `INVENTORY_OPERATION_INTENT_FIELDS` entry and
  // their intent digest is the digest of the whole payload — the S4 supplier
  // rule (A-10(b)).
  //
  // `customer.archive` and `customer.reactivate` have the SAME field list as
  // each other and as `supplier.archive` / `supplier.reactivate` — one uuid and
  // one non-nullable integer. Nothing about their shape tells them apart; the
  // op_code line of the signed stream does, which is why reactivation is its
  // own kind and not a direction flag (the S4 TL-3 ruling).
  'customer.create': Object.freeze([spec('customer_id', 'uuid'), ...CUSTOMER_TEXT]),
  'customer.update': Object.freeze([spec('customer_id', 'uuid'), spec('expected_revision', 'integer'), ...CUSTOMER_TEXT]),
  'customer.archive': Object.freeze([spec('customer_id', 'uuid'), spec('expected_revision', 'integer')]),
  'customer.reactivate': Object.freeze([spec('customer_id', 'uuid'), spec('expected_revision', 'integer')]),
  // P4-S2 (docs/PHASE_4_S2_CONTRACT.md A-05): the atomic sale commit. The
  // header binds the identities, the supplied dates, the SERVER-resolved FX
  // snapshot and the SERVER-computed totals; the group binds one row per line.
  //
  // `invoice_id` is in the payload and NOT in the intent, exactly as
  // `purchase.receive`'s `coverage_adjustment_id` is: the assertion must
  // authorize the invoice identity the routine will write, and a
  // server-minted UUID inside the INTENT would make two identical requests
  // two different commands.
  //
  // `invoice_number_seq` is deliberately absent from both. It is allocated as
  // `max + 1` under the sequence row's lock INSIDE the routine (P4-AL-31), so
  // it does not exist when the assertion is minted; signing it would mean
  // either minting inside the transaction or guessing a number.
  //
  // There is no cost, no value and no COGS field at any grain: the stock
  // writer computes the value from the locked level row, and the lock's §4
  // matrix makes a per-line cost the forbidden second truth.
  'sale.commit': withLines(
    [
      spec('sale_id', 'uuid'),
      // A STATED fact, part of the intent: `credit` or `cash` (P4-S2 D-01).
      spec('settlement_mode', 'code'),
      // NULL is a walk-in, admissible only for a `cash` sale.
      spec('customer_id', 'uuid', true),
      spec('warehouse_id', 'uuid'),
      spec('branch_id', 'uuid'),
      spec('invoice_id', 'uuid'),
      spec('document_date', 'integer'),
      spec('due_date', 'integer', true),
      spec('currency', 'code'),
      spec('rate_id', 'uuid', true),
      spec('rate_r10', 'integer'),
      spec('rate_source', 'code'),
      spec('rate_at', 'integer'),
      spec('subtotal_txn_minor', 'integer'),
      spec('discount_txn_minor', 'integer'),
      spec('tax_minor', 'integer'),
      spec('total_txn_minor', 'integer'),
      spec('total_base_minor', 'integer'),
      ...textWordSpecs('notes', true),
      spec('line_count', 'integer'),
    ],
    [
      spec('line_id', 'uuid'),
      // The STATED stock identity, and the whole of what a line may state
      // about it: the product, plus the merchant variant only for a product
      // that has them. The hidden base variant never leaves the server
      // (P3-AL-52), which is why a simple product's line carries a NULL
      // variant and the server resolves the stock key from the product.
      spec('product_id', 'uuid'),
      spec('merchant_variant_id', 'uuid', true),
      // The RESOLVED stock key: the base variant for a simple product, the
      // named merchant variant otherwise. Server-derived, so outside the
      // intent — a client cannot name it and a replay cannot depend on it.
      spec('variant_id', 'uuid'),
      spec('qty_q4', 'integer'),
      spec('discount_minor', 'integer'),
      spec('unit_price_c10', 'integer'),
      spec('net_txn_minor', 'integer'),
      spec('base_share_minor', 'integer'),
    ],
  ),
  // P4-S3 (docs/PHASE_4_S3_MIGRATION_DESIGN.md; lock P4-AL-18, OD-P4-02,
  // OD-P4-09). Each of the four streams is the argument list of its routine in
  // `0079`, in order and with its declared type, because the routine rebuilds
  // the claimed digest from those arguments and the two must agree field for
  // field:
  //
  //   pos_till_session_open  ARRAY['uuid','uuid','uuid','code','code','integer']
  //   pos_till_session_close ARRAY['uuid','integer']
  //   pos_cart_set_line      ARRAY['uuid','uuid','integer','uuid','uuid','integer','integer']
  //   pos_cart_remove_line   ARRAY['uuid','uuid']
  //
  // None of the four appears in `INVENTORY_OPERATION_INTENT_FIELDS`, and that
  // is a ruling rather than an omission. `0079` stores component 7 of the
  // assertion itself as the session's `open_intent_sha256` /
  // `close_intent_sha256` (`0079:836`, `0079:912`), so for these kinds the
  // payload digest IS the idempotency proof. It may be, because none of these
  // streams carries a server-resolved value that moves under a replay: there
  // is no price, no total, no rate and no clock value anywhere in them. The
  // one resolved field, the cart line's `variant_id`, is a FUNCTION of the
  // stated product (the hidden base variant of a simple product, P3-AL-52) and
  // resolves identically on a replay, which is exactly what a resolved
  // catalogue price does not do — the reason `sale.commit` needs the carve-out
  // and these do not.
  'pos.session_open': Object.freeze([
    spec('session_id', 'uuid'),
    spec('branch_id', 'uuid'),
    spec('warehouse_id', 'uuid'),
    // `pos_till_sessions_terminal_code_ck` is the registry-code regex
    // (`0079:362`), the same one `encodeCode` enforces, so the drawer's code
    // travels verbatim on both sides.
    spec('terminal_code', 'code'),
    // The routine signs `lower(p_currency_code)` while the column holds the
    // upper-case ISO code, so the client encodes the lower-case form. A `code`
    // field cannot be upper case: `encodeCode` would refuse it.
    spec('currency_code', 'code'),
    // The cash a human COUNTED in the drawer at the open, in minor units. It
    // is inside the signed payload deliberately: a replay presenting a
    // different float is a different command, which is what makes the figure
    // trustworthy at all.
    spec('opening_float_minor', 'integer'),
  ]),
  // The counted close, by the same argument. There is no expected-cash figure,
  // variance or over/short in the stream, because none is stored: each is
  // derived from this count, the opening float and the shift's cash payments,
  // and P4-AL-06 forbids a stored authoritative one.
  'pos.session_close': Object.freeze([spec('session_id', 'uuid'), spec('closing_count_minor', 'integer')]),
  // The whole of what a client may say about a basket line: identities, an
  // ordinal, a quantity and a discount REQUEST. There is no price, no line
  // total and no tax field here because `pos_cart_set_line` has no argument
  // for one — a forged price has nowhere to arrive.
  'pos.cart_set_line': Object.freeze([
    spec('session_id', 'uuid'),
    spec('line_id', 'uuid'),
    // The basket is append-only and ordinal-keyed with tombstones, so the
    // ordinal is part of the signed command rather than a position the server
    // picks.
    spec('line_no', 'integer'),
    spec('product_id', 'uuid'),
    // Resolved, and non-nullable: `0079` refuses a NULL variant outright.
    spec('variant_id', 'uuid'),
    // The routine signs `inventory_fixed_text(p_quantity, 4)`, so the field
    // carries the quantity × 10^4 as an exact integer — the P3-S3 `qty_q4`
    // binding, unchanged.
    spec('qty_q4', 'integer'),
    // A REQUEST in the minor units of the session's currency, not a granted
    // discount: `0079` deliberately does not cap it against a gross the
    // basket does not store, and `sale_items_discount_ck` is where the cap
    // lives (R-P4-S3-03).
    spec('requested_discount_minor', 'integer'),
  ]),
  'pos.cart_remove_line': Object.freeze([spec('session_id', 'uuid'), spec('line_id', 'uuid')]),
};

/**
 * The server-derived fields (PHASE_3_S3_CONTRACT A-10(b)). The intent digest
 * — the idempotency proof a document header stores — is the `invpl/1` digest
 * of every OTHER field: what the client asked for, never what the server
 * computed from current state, and never a clock value.
 */
export const INVENTORY_SERVER_DERIVED_FIELDS: readonly string[] = ['expected_value', 'opening_balance_id', 'position_minor', 'variance_q4'];

/**
 * The P3-S4 intents (PHASE_3_S4_CONTRACT A-10(b)). Every supplier and draft
 * field is the client's, so those intents are their whole payloads. A receipt
 * is the exception: its client intent is `purchase_id`, `warehouse_id` and
 * `draft_revision` only, and every other field — the supplier revision, the
 * FX snapshot, the totals, the coverage and every line — is server-derived.
 * A group whose count field is derived is derived as a whole.
 */
export const INVENTORY_OPERATION_INTENT_FIELDS: Readonly<Partial<Record<InventoryOperationCode, readonly string[]>>> = Object.freeze({
  'purchase.receive': Object.freeze(['purchase_id', 'warehouse_id', 'draft_revision']),
  // P3-S5 (PHASE_3_S5_CONTRACT A-17): a return's intent is its header
  // identity, date and reason, and per line its id, purchase line and
  // quantity; every amount, the credit note id and the variant are derived.
  // A reversal's intent is the purchase, its warehouse, the date and the
  // reason; its lines are the purchase's, so the whole group is derived.
  'purchase.return': Object.freeze([
    'return_id',
    'purchase_id',
    'warehouse_id',
    'document_date',
    ...Array.from({ length: 8 }, (_, i) => `reason_w${i + 1}`),
    'line_count',
    'return_line_id',
    'purchase_line_id',
    'qty_q4',
  ]),
  'purchase.reverse': Object.freeze(['purchase_id', 'warehouse_id', 'reversal_date', ...Array.from({ length: 8 }, (_, i) => `reason_w${i + 1}`)]),
  // P3-S6 (PHASE_3_S6_CONTRACT A-16): the three settlement intents are their
  // client-stated fields only; every FX snapshot, base, release, dust and
  // realized amount — and a payment's posting account and allocation
  // warehouses — is derived. The four payment-method kinds have no entry:
  // every field is intent, so their intent is the payload itself (the S4
  // supplier pattern).
  'supplier.pay': Object.freeze([
    'payment_id',
    'supplier_id',
    'payment_method_id',
    'payment_date',
    'currency',
    'amount',
    ...Array.from({ length: 8 }, (_, i) => `reference_w${i + 1}`),
    'allocation_count',
    'allocation_id',
    'purchase_id',
    'payment_amount',
    'applied',
  ]),
  'supplier.allocate_credit': Object.freeze(['allocation_id', 'credit_note_id', 'purchase_id', 'allocation_date', 'consumed', 'applied']),
  'supplier.receive_refund': Object.freeze([
    'refund_id',
    'credit_note_id',
    'payment_method_id',
    'refund_date',
    'consumed',
    'receipt_currency',
    'receipt_amount',
    ...Array.from({ length: 8 }, (_, i) => `reference_w${i + 1}`),
  ]),
  // Phase 3 corrective (0072, TD-16): the purchase, the date, the reason and
  // the stated residue; the chain point and the released base are derived.
  'purchase.write_off_residue': Object.freeze(['purchase_id', 'write_off_date', ...Array.from({ length: 8 }, (_, i) => `reason_w${i + 1}`), 'residue']),
  // P4-S2 (docs/PHASE_4_S2_CONTRACT.md A-06): the sale commit's intent is
  // WHAT THE CLIENT ASKED FOR and nothing else — the sale's own id, the
  // customer, the warehouse, both supplied dates, the stated (zero) tax, the
  // notes, and per line the line's id, its variant, its quantity and its
  // requested discount.
  //
  // Everything else is server-derived and therefore OUTSIDE the fingerprint:
  // the branch (resolved from the warehouse), the invoice id (minted), the
  // currency and the whole FX snapshot (read from the registry), every total,
  // and per line the resolved catalogue price, the net and the base share. A
  // replay must be the same command even though the catalogue price, the rate
  // and the stock have all moved since — and a fingerprint that covered the
  // resolved price would make every price change a false conflict.
  //
  // `tax_minor` IS intent, because `OD-03` is open and the client states the
  // zero rather than the server defaulting it. `document_date` and `due_date`
  // ARE intent, because `[[daftar-a-command-must-not-read-the-clock]]`: a
  // date a fingerprint covers is supplied by the caller and is part of the
  // intent, and no layer — DTO, schema, service, engine or trusted database
  // command — resolves one from a clock.
  'sale.commit': Object.freeze([
    'sale_id',
    'settlement_mode',
    'customer_id',
    'warehouse_id',
    'document_date',
    'due_date',
    'tax_minor',
    ...Array.from({ length: 8 }, (_, i) => `notes_w${i + 1}`),
    'line_count',
    'line_id',
    'product_id',
    'merchant_variant_id',
    'qty_q4',
    'discount_minor',
  ]),
});

/** The intent schema of an operation kind: its schema with the server-derived fields removed, header and group alike. */
export function inventoryIntentSchema(opCode: InventoryOperationCode): InventoryPayloadSchema {
  if (!isInventoryOperationCode(opCode)) refuse('names an unregistered operation kind');
  const schema = INVENTORY_PAYLOAD_SCHEMAS[opCode];
  const only = INVENTORY_OPERATION_INTENT_FIELDS[opCode];
  const keep = (s: InventoryPayloadFieldSpec): boolean => !INVENTORY_SERVER_DERIVED_FIELDS.includes(s.name) && (only === undefined || only.includes(s.name));
  const header = schema.filter(keep);
  const repeat = schema.repeat;
  if (repeat === undefined || !header.some((s) => s.name === repeat.countField)) return Object.freeze(header);
  const lineFields = repeat.fields.filter(keep);
  const trailer = schema.trailer;
  if (trailer === undefined || !keep(trailer.countField)) return withGroup(header, repeat.countField, lineFields);
  const perLine = trailer.perLine !== undefined && keep(trailer.perLine) ? trailer.perLine : undefined;
  return withLinesAndTrailer(header, lineFields, {
    countField: trailer.countField,
    fields: trailer.fields.filter(keep),
    ...(perLine === undefined ? {} : { perLine }),
  });
}

/** A canonicalized payload: the operation it is for, its exact bytes and their digest. */
export interface InventoryPayload {
  readonly opCode: InventoryOperationCode;
  readonly bytes: Buffer;
  /** Lowercase hex SHA-256 of `bytes` — component 7 of the assertion. */
  readonly sha256: string;
}

const refuse = (what: string): never => {
  throw new InventoryError('inventory.payload_invalid', `invpl/1 payload ${what}`);
};

/** True for a registered operation code (P3-S1, P3-S3, P3-S4, P3-S5, P3-S6 or the corrective pass). Refuses anything else, including a wildcard. */
export function isInventoryOperationCode(value: unknown): value is InventoryOperationCode {
  return typeof value === 'string' && (INVENTORY_OPERATION_CODES as readonly string[]).includes(value);
}

function encodeUuid(value: unknown, what: string): string {
  if (typeof value !== 'string' || !CANONICAL_UUID_RE.test(value)) refuse(`${what} is not a canonical lowercase uuid`);
  return value as string;
}

function encodeInteger(value: unknown, what: string): string {
  let n: bigint;
  if (typeof value === 'bigint') {
    n = value;
  } else if (typeof value === 'number' && Number.isSafeInteger(value)) {
    // `BigInt(-0)` is `0n`, so negative zero encodes as `0`, never `-0`.
    n = BigInt(value);
  } else {
    return refuse(`${what} is not an integer`);
  }
  if (n < INT8_MIN || n > INT8_MAX) refuse(`${what} is outside the bigint range`);
  // `bigint.toString(10)` is exactly the canonical form: no `+`, no leading
  // zero, `-` only when negative, zero as `0`.
  return n.toString(10);
}

function encodeCode(value: unknown, what: string): string {
  if (typeof value !== 'string' || !REGISTRY_CODE_RE.test(value)) refuse(`${what} is not a registry code matching ^[a-z][a-z0-9_]{0,31}$`);
  return value as string;
}

/**
 * The bytes of one field line, without its terminating LF. Exported for the
 * P3-S3 builders, so every stream has exactly one encoder.
 */
export function encodeInventoryField(field: InventoryPayloadField, fieldSpec: InventoryPayloadFieldSpec, index: number): Buffer {
  const what = `field ${index + 1} (${fieldSpec.name})`;
  if (field.kind === 'null') {
    if (!fieldSpec.nullable) refuse(`${what} may not be NULL`);
    return Buffer.from([NUL]);
  }
  if (field.kind !== fieldSpec.type) refuse(`${what} must be of type ${fieldSpec.type}`);
  switch (field.kind) {
    case 'uuid':
      return Buffer.from(encodeUuid(field.value, what), 'ascii');
    case 'boolean':
      if (typeof field.value !== 'boolean') refuse(`${what} is not a boolean`);
      return Buffer.from(field.value ? 'true' : 'false', 'ascii');
    case 'integer':
      return Buffer.from(encodeInteger(field.value, what), 'ascii');
    case 'code':
      return Buffer.from(encodeCode(field.value, what), 'ascii');
  }
}

/**
 * The exact `invpl/1` byte stream for one command.
 *
 * `fields` are positional and must follow `INVENTORY_PAYLOAD_SCHEMAS[opCode]`
 * exactly — count, order, type and nullability. Anything else is refused
 * before a single byte is produced.
 */
export function canonicalInventoryPayload(
  opCode: InventoryOperationCode,
  tenantId: string,
  businessId: string,
  fields: readonly InventoryPayloadField[],
): Buffer {
  if (!isInventoryOperationCode(opCode) || !OPERATION_CODE_RE.test(opCode)) refuse('names an unregistered operation kind');
  return canonicalStream(opCode, tenantId, businessId, INVENTORY_PAYLOAD_SCHEMAS[opCode], fields);
}

/**
 * The `invpl/1` stream of a command's INTENT (PHASE_3_S3_CONTRACT A-10(b)):
 * the same encoder, op code, tenant and business, over the fields of
 * `inventoryIntentSchema(opCode)`. It is the idempotency proof a document
 * header stores, and never an assertion digest.
 */
export function canonicalInventoryIntent(
  opCode: InventoryOperationCode,
  tenantId: string,
  businessId: string,
  fields: readonly InventoryPayloadField[],
): Buffer {
  if (!isInventoryOperationCode(opCode) || !OPERATION_CODE_RE.test(opCode)) refuse('names an unregistered operation kind');
  return canonicalStream(opCode, tenantId, businessId, inventoryIntentSchema(opCode), fields);
}

/**
 * The spec of every field of the stream, in order: the header, then the
 * repeating group as many times as its count field says. A count that does
 * not match the number of fields supplied is refused, never trusted.
 */
function expandSchema(
  opCode: InventoryOperationCode,
  schema: InventoryPayloadSchema,
  fields: readonly InventoryPayloadField[],
): readonly InventoryPayloadFieldSpec[] {
  const repeat = schema.repeat;
  if (repeat === undefined) {
    if (schema.trailer !== undefined) return refuse(`schema for ${opCode} has a trailer without lines`);
    if (fields.length !== schema.length) refuse(`for ${opCode} requires exactly ${schema.length} fields`);
    return schema;
  }
  const at = schema.findIndex((s) => s.name === repeat.countField);
  const countSpec = schema[at];
  if (countSpec === undefined || countSpec.type !== 'integer' || countSpec.nullable || repeat.fields.length === 0) {
    return refuse(`schema for ${opCode} has a malformed repeating group`);
  }
  const countField = fields[at];
  if (countField === undefined || countField.kind !== 'integer') return refuse(`field ${at + 1} (${repeat.countField}) must be an integer`);
  const count = BigInt(encodeInteger(countField.value, `field ${at + 1} (${repeat.countField})`));
  if (count < 0n) refuse(`field ${at + 1} (${repeat.countField}) may not be negative`);
  const trailer = schema.trailer;
  if (trailer !== undefined) return expandTrailer(opCode, schema, repeat, trailer, count, fields);
  if (BigInt(fields.length) !== BigInt(schema.length) + count * BigInt(repeat.fields.length)) {
    refuse(`for ${opCode} requires ${schema.length} header fields plus ${repeat.fields.length} per line`);
  }
  const out: InventoryPayloadFieldSpec[] = [...schema];
  for (let i = 0n; i < count; i += 1n) out.push(...repeat.fields);
  return out;
}

/**
 * The stream of a schema with a trailer group (`purchase.draft`, A-09): the
 * header, the lines, the trailer's count, then each trailer group followed —
 * when the trailer has a per-line field — by one such field per line.
 */
function expandTrailer(
  opCode: InventoryOperationCode,
  schema: InventoryPayloadSchema,
  repeat: InventoryPayloadRepeat,
  trailer: InventoryPayloadTrailer,
  lineCount: bigint,
  fields: readonly InventoryPayloadField[],
): readonly InventoryPayloadFieldSpec[] {
  const tc = trailer.countField;
  if (tc.type !== 'integer' || tc.nullable || trailer.fields.length === 0) return refuse(`schema for ${opCode} has a malformed trailer group`);
  const before = BigInt(schema.length) + lineCount * BigInt(repeat.fields.length);
  if (BigInt(fields.length) <= before) return refuse(`for ${opCode} requires the ${tc.name} field after the lines`);
  // The index as an array position without a float conversion (P3-AL-08):
  // `before < fields.length`, so exactly one position matches.
  const at = fields.findIndex((_, i) => BigInt(i) === before);
  const countField = fields[at];
  if (countField === undefined || countField.kind !== 'integer') return refuse(`field ${at + 1} (${tc.name}) must be an integer`);
  const count = BigInt(encodeInteger(countField.value, `field ${at + 1} (${tc.name})`));
  if (count < 0n) refuse(`field ${at + 1} (${tc.name}) may not be negative`);
  const perLine = trailer.perLine;
  const width = BigInt(trailer.fields.length) + (perLine === undefined ? 0n : lineCount);
  if (BigInt(fields.length) !== before + 1n + count * width) {
    refuse(`for ${opCode} requires ${trailer.fields.length} fields per ${tc.name} group${perLine === undefined ? '' : ' plus one per line'}`);
  }
  const out: InventoryPayloadFieldSpec[] = [...schema];
  for (let i = 0n; i < lineCount; i += 1n) out.push(...repeat.fields);
  out.push(tc);
  for (let k = 0n; k < count; k += 1n) {
    out.push(...trailer.fields);
    if (perLine !== undefined) for (let i = 0n; i < lineCount; i += 1n) out.push(perLine);
  }
  return out;
}

function canonicalStream(
  opCode: InventoryOperationCode,
  tenantId: string,
  businessId: string,
  schema: InventoryPayloadSchema,
  fields: readonly InventoryPayloadField[],
): Buffer {
  const specs = expandSchema(opCode, schema, fields);

  const lines: Buffer[] = [
    Buffer.from(INVPL_DOMAIN, 'ascii'),
    Buffer.from(opCode, 'ascii'),
    Buffer.from(encodeUuid(tenantId, 'tenant'), 'ascii'),
    Buffer.from(encodeUuid(businessId, 'business'), 'ascii'),
  ];
  specs.forEach((s, i) => {
    const field = fields[i] ?? refuse(`field ${i + 1} is missing`);
    lines.push(encodeInventoryField(field, s, i));
  });

  // §F: no line may contain LF, and only a NULL line may contain NUL — and
  // then as its only byte. Every encoder above already makes this
  // impossible; this is the assertion the lock requires, so a future encoder
  // cannot quietly break the framing.
  for (const line of lines) {
    const isNull = line.length === 1 && line[0] === NUL;
    if (line.length === 0 || line.includes(LF) || (!isNull && line.includes(NUL))) refuse('produced an unframeable line');
  }

  const out: Buffer[] = [];
  for (const line of lines) out.push(line, Buffer.from([LF]));
  return Buffer.concat(out);
}

/** Lowercase hex SHA-256 of the `invpl/1` stream. */
export function inventoryPayloadSha256(opCode: InventoryOperationCode, tenantId: string, businessId: string, fields: readonly InventoryPayloadField[]): string {
  return createHash('sha256')
    .update(canonicalInventoryPayload(opCode, tenantId, businessId, fields))
    .digest('hex');
}

/** Lowercase hex SHA-256 of the intent stream (`canonicalInventoryIntent`): the value a document header stores as `intent_sha256`. */
export function inventoryIntentSha256(opCode: InventoryOperationCode, tenantId: string, businessId: string, fields: readonly InventoryPayloadField[]): string {
  return createHash('sha256')
    .update(canonicalInventoryIntent(opCode, tenantId, businessId, fields))
    .digest('hex');
}

/** The canonical bytes and digest of one command (`canonicalInventoryPayload` then SHA-256). */
export function buildInventoryPayload(
  opCode: InventoryOperationCode,
  tenantId: string,
  businessId: string,
  fields: readonly InventoryPayloadField[],
): InventoryPayload {
  const bytes = canonicalInventoryPayload(opCode, tenantId, businessId, fields);
  return { opCode, bytes, sha256: createHash('sha256').update(bytes).digest('hex') };
}

export interface ConfigureProductPayloadInput {
  readonly tenantId: string;
  readonly businessId: string;
  readonly productId: string;
  readonly trackInventory: boolean;
  /** NULL when the command leaves the product without a canonical unit. */
  readonly unitCode: string | null;
  /** NULL together with, or independently of, `unitCode`; the database decides validity after verification. */
  readonly unitDecimals: number | null;
}

export interface WarehouseBranchPayloadInput {
  readonly tenantId: string;
  readonly businessId: string;
  readonly warehouseId: string;
  readonly branchId: string;
}

/** `inventory.configure_product`: product_id, track_inventory, unit_code, unit_decimals. */
export function configureProductPayload(input: ConfigureProductPayloadInput): InventoryPayload {
  return buildInventoryPayload('inventory.configure_product', input.tenantId, input.businessId, [
    { kind: 'uuid', value: input.productId },
    { kind: 'boolean', value: input.trackInventory },
    input.unitCode === null ? { kind: 'null' } : { kind: 'code', value: input.unitCode },
    input.unitDecimals === null ? { kind: 'null' } : { kind: 'integer', value: input.unitDecimals },
  ]);
}

/** `structure.associate_warehouse_branch`: warehouse_id, branch_id. */
export function associateWarehouseBranchPayload(input: WarehouseBranchPayloadInput): InventoryPayload {
  return buildInventoryPayload('structure.associate_warehouse_branch', input.tenantId, input.businessId, [
    { kind: 'uuid', value: input.warehouseId },
    { kind: 'uuid', value: input.branchId },
  ]);
}

/**
 * `structure.dissociate_warehouse_branch`: warehouse_id, branch_id. Same
 * field shape as associate; the op_code line keeps the digests apart.
 */
export function dissociateWarehouseBranchPayload(input: WarehouseBranchPayloadInput): InventoryPayload {
  return buildInventoryPayload('structure.dissociate_warehouse_branch', input.tenantId, input.businessId, [
    { kind: 'uuid', value: input.warehouseId },
    { kind: 'uuid', value: input.branchId },
  ]);
}
