/**
 * `invpl/1` — the canonical inventory command payload (P3-AL-55 §F).
 *
 * An `invctl/1` assertion authorizes THE PAYLOAD THE ROUTINE ACTUALLY
 * RECEIVES. Component 7 of the assertion is the SHA-256 of the stream built
 * here; the database routine rebuilds the same stream from its OWN arguments
 * and refuses a mismatch (`inventory.assertion_payload_mismatch`) before any
 * decision-relevant read or write. A caller-supplied digest is never trusted
 * by itself — the principle of `acctfp/1` (`packages/accounting/src/fingerprint.ts`).
 *
 * The stream, every line terminated by the single byte 0x0A (LF), the last
 * one included:
 *
 *   'invpl/1' LF  op_code LF  tenant LF  business LF  field_1 LF … field_n LF
 *
 * Field encoding — no implementer choice:
 *
 *   UUID      36 bytes, lowercase hex, hyphenated 8-4-4-4-12
 *   boolean   ASCII `true` / `false`
 *   integer   base-10 ASCII; `-` only for a negative value; no `+`, no leading
 *             zero; zero is `0`
 *   code      its bytes exactly; must already match ^[a-z][a-z0-9_]{0,31}$
 *   NULL      the single byte 0x00 and nothing else on that line
 *
 * Non-canonical input is REFUSED, never normalized: an uppercase UUID, a code
 * with a capital letter or a trailing space, a fractional or unsafe integer.
 * Normalizing here would let the application sign bytes the database would
 * never produce from the same arguments, and the two implementations would
 * agree with themselves while disagreeing with each other.
 *
 * The same specification is implemented in SQL; both are tested against
 * `vectors/invpl-vectors.json`, generated by `scripts/generate-vectors.ts`.
 */
import { createHash } from 'node:crypto';
import { InventoryError } from './errors';

/**
 * The operation kinds P3-S1 registers (P3-AL-55 §E). Later slices register
 * their own kinds together with the routine that consumes them; a kind listed
 * here without a routine would be an authority nothing refuses.
 */
export type InventoryOperationCode = 'inventory.configure_product' | 'structure.associate_warehouse_branch' | 'structure.dissociate_warehouse_branch';

export const INVENTORY_OPERATION_CODES: readonly InventoryOperationCode[] = [
  'inventory.configure_product',
  'structure.associate_warehouse_branch',
  'structure.dissociate_warehouse_branch',
];

/** The literal first line of every stream. */
export const INVPL_DOMAIN = 'invpl/1';

/** The registry's own CHECK on `inventory_operation_kinds.op_code`. */
export const OPERATION_CODE_RE = /^[a-z]+(\.[a-z_]+)+$/;
/** Canonical UUID: lowercase only. The pattern the database enforces. */
export const CANONICAL_UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
/** The `units.unit_code` registry pattern (P3-AL-05). */
export const REGISTRY_CODE_RE = /^[a-z][a-z0-9_]{0,31}$/;

/** The range of PostgreSQL `bigint`, the widest integer a routine argument can be. */
const INT8_MIN = -(2n ** 63n);
const INT8_MAX = 2n ** 63n - 1n;

const LF = 0x0a;
const NUL = 0x00;

/** One typed field of the stream. The type decides the encoding, never the value. */
export type InventoryPayloadField =
  | { readonly kind: 'uuid'; readonly value: string }
  | { readonly kind: 'boolean'; readonly value: boolean }
  | { readonly kind: 'integer'; readonly value: number | bigint }
  | { readonly kind: 'code'; readonly value: string }
  | { readonly kind: 'null' };

export type InventoryPayloadFieldType = Exclude<InventoryPayloadField['kind'], 'null'>;

export interface InventoryPayloadFieldSpec {
  readonly name: string;
  readonly type: InventoryPayloadFieldType;
  readonly nullable: boolean;
}

/**
 * Field order per operation kind (P3-AL-55 §F, P3-S1 table). The SQL
 * canonicalizer takes the routine's arguments in exactly this order.
 */
export const INVENTORY_PAYLOAD_SCHEMAS: Readonly<Record<InventoryOperationCode, readonly InventoryPayloadFieldSpec[]>> = {
  'inventory.configure_product': [
    { name: 'product_id', type: 'uuid', nullable: false },
    { name: 'track_inventory', type: 'boolean', nullable: false },
    { name: 'unit_code', type: 'code', nullable: true },
    { name: 'unit_decimals', type: 'integer', nullable: true },
  ],
  'structure.associate_warehouse_branch': [
    { name: 'warehouse_id', type: 'uuid', nullable: false },
    { name: 'branch_id', type: 'uuid', nullable: false },
  ],
  'structure.dissociate_warehouse_branch': [
    { name: 'warehouse_id', type: 'uuid', nullable: false },
    { name: 'branch_id', type: 'uuid', nullable: false },
  ],
};

/** A canonicalized payload: the operation it is for, its exact bytes and their digest. */
export interface InventoryPayload {
  readonly opCode: InventoryOperationCode;
  readonly bytes: Buffer;
  /** Lowercase hex SHA-256 of `bytes` — component 7 of the assertion. */
  readonly sha256: string;
}

const refuse = (what: string): never => {
  throw new InventoryError('inventory.payload_invalid', `invpl/1 payload ${what}`);
};

/** True for a registered P3-S1 operation code. Refuses anything else, including a wildcard. */
export function isInventoryOperationCode(value: unknown): value is InventoryOperationCode {
  return typeof value === 'string' && (INVENTORY_OPERATION_CODES as readonly string[]).includes(value);
}

function encodeUuid(value: unknown, what: string): string {
  if (typeof value !== 'string' || !CANONICAL_UUID_RE.test(value)) refuse(`${what} is not a canonical lowercase uuid`);
  return value as string;
}

function encodeInteger(value: unknown, what: string): string {
  let n: bigint;
  if (typeof value === 'bigint') {
    n = value;
  } else if (typeof value === 'number' && Number.isSafeInteger(value)) {
    // `BigInt(-0)` is `0n`, so negative zero encodes as `0`, never `-0`.
    n = BigInt(value);
  } else {
    return refuse(`${what} is not an integer`);
  }
  if (n < INT8_MIN || n > INT8_MAX) refuse(`${what} is outside the bigint range`);
  // `bigint.toString(10)` is exactly the canonical form: no `+`, no leading
  // zero, `-` only when negative, zero as `0`.
  return n.toString(10);
}

function encodeCode(value: unknown, what: string): string {
  if (typeof value !== 'string' || !REGISTRY_CODE_RE.test(value)) refuse(`${what} is not a registry code matching ^[a-z][a-z0-9_]{0,31}$`);
  return value as string;
}

/** The bytes of one field line, without its terminating LF. */
function encodeField(field: InventoryPayloadField, spec: InventoryPayloadFieldSpec, index: number): Buffer {
  const what = `field ${index + 1} (${spec.name})`;
  if (field.kind === 'null') {
    if (!spec.nullable) refuse(`${what} may not be NULL`);
    return Buffer.from([NUL]);
  }
  if (field.kind !== spec.type) refuse(`${what} must be of type ${spec.type}`);
  switch (field.kind) {
    case 'uuid':
      return Buffer.from(encodeUuid(field.value, what), 'ascii');
    case 'boolean':
      if (typeof field.value !== 'boolean') refuse(`${what} is not a boolean`);
      return Buffer.from(field.value ? 'true' : 'false', 'ascii');
    case 'integer':
      return Buffer.from(encodeInteger(field.value, what), 'ascii');
    case 'code':
      return Buffer.from(encodeCode(field.value, what), 'ascii');
  }
}

/**
 * The exact `invpl/1` byte stream for one command.
 *
 * `fields` are positional and must follow `INVENTORY_PAYLOAD_SCHEMAS[opCode]`
 * exactly — count, order, type and nullability. Anything else is refused
 * before a single byte is produced.
 */
export function canonicalInventoryPayload(
  opCode: InventoryOperationCode,
  tenantId: string,
  businessId: string,
  fields: readonly InventoryPayloadField[],
): Buffer {
  if (!isInventoryOperationCode(opCode) || !OPERATION_CODE_RE.test(opCode)) refuse('names an unregistered operation kind');
  const schema = INVENTORY_PAYLOAD_SCHEMAS[opCode];
  if (fields.length !== schema.length) refuse(`for ${opCode} requires exactly ${schema.length} fields`);

  const lines: Buffer[] = [
    Buffer.from(INVPL_DOMAIN, 'ascii'),
    Buffer.from(opCode, 'ascii'),
    Buffer.from(encodeUuid(tenantId, 'tenant'), 'ascii'),
    Buffer.from(encodeUuid(businessId, 'business'), 'ascii'),
  ];
  schema.forEach((spec, i) => {
    const field = fields[i] ?? refuse(`field ${i + 1} is missing`);
    lines.push(encodeField(field, spec, i));
  });

  // §F: no line may contain LF, and only a NULL line may contain NUL — and
  // then as its only byte. Every encoder above already makes this
  // impossible; this is the assertion the lock requires, so a future encoder
  // cannot quietly break the framing.
  for (const line of lines) {
    const isNull = line.length === 1 && line[0] === NUL;
    if (line.length === 0 || line.includes(LF) || (!isNull && line.includes(NUL))) refuse('produced an unframeable line');
  }

  const out: Buffer[] = [];
  for (const line of lines) out.push(line, Buffer.from([LF]));
  return Buffer.concat(out);
}

/** Lowercase hex SHA-256 of the `invpl/1` stream. */
export function inventoryPayloadSha256(opCode: InventoryOperationCode, tenantId: string, businessId: string, fields: readonly InventoryPayloadField[]): string {
  return createHash('sha256')
    .update(canonicalInventoryPayload(opCode, tenantId, businessId, fields))
    .digest('hex');
}

function build(opCode: InventoryOperationCode, tenantId: string, businessId: string, fields: readonly InventoryPayloadField[]): InventoryPayload {
  const bytes = canonicalInventoryPayload(opCode, tenantId, businessId, fields);
  return { opCode, bytes, sha256: createHash('sha256').update(bytes).digest('hex') };
}

export interface ConfigureProductPayloadInput {
  readonly tenantId: string;
  readonly businessId: string;
  readonly productId: string;
  readonly trackInventory: boolean;
  /** NULL when the command leaves the product without a canonical unit. */
  readonly unitCode: string | null;
  /** NULL together with, or independently of, `unitCode`; the database decides validity after verification. */
  readonly unitDecimals: number | null;
}

export interface WarehouseBranchPayloadInput {
  readonly tenantId: string;
  readonly businessId: string;
  readonly warehouseId: string;
  readonly branchId: string;
}

/** `inventory.configure_product`: product_id, track_inventory, unit_code, unit_decimals. */
export function configureProductPayload(input: ConfigureProductPayloadInput): InventoryPayload {
  return build('inventory.configure_product', input.tenantId, input.businessId, [
    { kind: 'uuid', value: input.productId },
    { kind: 'boolean', value: input.trackInventory },
    input.unitCode === null ? { kind: 'null' } : { kind: 'code', value: input.unitCode },
    input.unitDecimals === null ? { kind: 'null' } : { kind: 'integer', value: input.unitDecimals },
  ]);
}

/** `structure.associate_warehouse_branch`: warehouse_id, branch_id. */
export function associateWarehouseBranchPayload(input: WarehouseBranchPayloadInput): InventoryPayload {
  return build('structure.associate_warehouse_branch', input.tenantId, input.businessId, [
    { kind: 'uuid', value: input.warehouseId },
    { kind: 'uuid', value: input.branchId },
  ]);
}

/**
 * `structure.dissociate_warehouse_branch`: warehouse_id, branch_id. Same
 * field shape as associate; the op_code line keeps the digests apart.
 */
export function dissociateWarehouseBranchPayload(input: WarehouseBranchPayloadInput): InventoryPayload {
  return build('structure.dissociate_warehouse_branch', input.tenantId, input.businessId, [
    { kind: 'uuid', value: input.warehouseId },
    { kind: 'uuid', value: input.branchId },
  ]);
}
