/**
 * Regenerates `fxrate-vectors.json`.
 *
 * Run with `npx tsx packages/accounting/vectors/generate-fxrate.ts`. The
 * inputs below are the specification's interesting cases; the expected bytes
 * and digest are computed by the TypeScript canonicalizer and then
 * independently reproduced by the PostgreSQL one in
 * `tests/integration/accounting-fx-parity.test.ts`. Regenerating is therefore
 * only legitimate when the SPEC changed — if a regeneration silently changes
 * an existing digest, the parity test against the database fails, which is
 * exactly the alarm it exists to raise.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { computeFxRateFingerprint, fxRateCanonicalStream, type FxRateFacts } from '../src/fx-rate';

interface RawCase {
  name: string;
  why: string;
  tenantId: string;
  businessId: string;
  rateId: string;
  fromCurrency: string;
  toCurrency: string;
  rate: string;
  effectiveAt: string;
  source: 'manual';
}

const T = '3f2504e0-4f89-41d3-9a0c-0305e82c3301';
const B = '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d';
const R1 = '6ba7b810-9dad-11d1-80b4-00c04fd430c8';
const R2 = '1b4e28ba-2fa1-11d2-9a0c-0305e82c3301';

const base = (over: Partial<RawCase>): RawCase => ({
  name: 'unnamed',
  why: '',
  tenantId: T,
  businessId: B,
  rateId: R1,
  fromCurrency: 'USD',
  toCurrency: 'ILS',
  rate: '3.71',
  effectiveAt: '2026-09-22T10:00:00Z',
  source: 'manual',
  ...over,
});

const cases: RawCase[] = [
  base({
    name: 'usd-ils-plain',
    why: 'The ordinary case: a rate entered as "3.71" canonicalizes to ten fraction digits, which is the scale NUMERIC(20,10) stores.',
  }),
  base({
    name: 'rate-one-bare',
    why: '"1" — §59. A rate of exactly one between two DIFFERENT currencies is a real fact (a peg), and it must hash identically however it was written.',
    rate: '1',
    fromCurrency: 'USD',
    toCurrency: 'EUR',
  }),
  base({
    name: 'rate-one-single-decimal',
    why: '"1.0" — the same value, written differently. It must produce the SAME bytes as rate-one-bare: two financial values may never hash differently because formatting differed.',
    rate: '1.0',
    fromCurrency: 'USD',
    toCurrency: 'EUR',
  }),
  base({
    name: 'rate-one-full-scale',
    why: '"1.0000000000" — the storage form. Third spelling, same bytes.',
    rate: '1.0000000000',
    fromCurrency: 'USD',
    toCurrency: 'EUR',
  }),
  base({
    name: 'sub-one-rate',
    why: 'A rate below one (JOD is stronger than USD). Proves the leading zero is present: ".7090000000" and "0.7090000000" are different bytes, and only one of them is what PostgreSQL stores.',
    rate: '0.709',
    fromCurrency: 'USD',
    toCurrency: 'JOD',
    rateId: R2,
  }),
  base({
    name: 'ten-fraction-digits',
    why: 'The full contract scale, at the LBP end of the range where the digits actually matter.',
    rate: '0.0000254013',
    fromCurrency: 'LBP',
    toCurrency: 'USD',
    rateId: R2,
  }),
  base({
    name: 'uppercase-uuids-and-lowercase-currency',
    why: 'Identifiers are lowercased and currencies uppercased before hashing, so the same fact stated in either case is one fact.',
    tenantId: T.toUpperCase(),
    businessId: B.toUpperCase(),
    rateId: R1.toUpperCase(),
    fromCurrency: 'usd',
    toCurrency: 'try',
    rate: '10.9',
  }),
  base({
    name: 'direction-is-part-of-identity',
    why: 'USD->ILS and ILS->USD are DIFFERENT facts at the same instant. §19 forbids inferring one from the other, and the fingerprint must agree: swapping the pair must change the digest.',
    fromCurrency: 'ILS',
    toCurrency: 'USD',
    rate: '0.2695417790',
  }),
  base({
    name: 'epoch-second-boundary',
    why: 'A whole second at midnight UTC. §16 refuses sub-second precision physically; this pins the RFC3339 form the fingerprint uses.',
    effectiveAt: '2026-01-01T00:00:00Z',
    rate: '3.6500000000',
  }),
];

const toFacts = (c: RawCase): FxRateFacts => ({
  tenantId: c.tenantId,
  businessId: c.businessId,
  rateId: c.rateId,
  fromCurrency: c.fromCurrency,
  toCurrency: c.toCurrency,
  rate: c.rate,
  effectiveAt: new Date(c.effectiveAt),
  source: c.source,
});

const out = {
  spec: 'fxrate/1',
  note: 'Generated by packages/accounting/vectors/generate-fxrate.ts. One source for BOTH the TypeScript and PostgreSQL FX canonicalizers (directive §32, §59).',
  cases: cases.map((c) => {
    const facts = toFacts(c);
    return {
      name: c.name,
      why: c.why,
      facts: {
        tenantId: c.tenantId,
        businessId: c.businessId,
        rateId: c.rateId,
        fromCurrency: c.fromCurrency,
        toCurrency: c.toCurrency,
        rate: c.rate,
        effectiveAt: c.effectiveAt,
        source: c.source,
      },
      canonicalHex: fxRateCanonicalStream(facts).toString('hex'),
      fingerprint: computeFxRateFingerprint(facts),
    };
  }),
};

writeFileSync(join(__dirname, 'fxrate-vectors.json'), `${JSON.stringify(out, null, 2)}\n`, 'utf8');
process.stdout.write(`wrote ${out.cases.length} vectors\n`);
